FROM node:14

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD package.json yarn.lock /usr/src/app
RUN yarn

ADD . /usr/src/app
RUN chown -R node:node /usr/src/app

USER node
CMD ["yarn", "db:migrate"]

